### ISSUE TITLE
An entry in `setup.cfg` makes debugger unable to start in PyCharm

### ISSUE THREAD

**Issue by guillaume-chevalier** [Neuraxio/New-Empty-Python-Project-Base#1]
For some reason, the debugger starts working in the created projects when we remove these lines: 
```
[tool:pytest]
addopts = --cov=project/
```

**Comment by alexbrillant** [comment]
true story. was about to create this issue.

**Comment by alexbrillant** [comment]
![Screenshot from 2020-05-05 12-20-32](https://user-images.githubusercontent.com/19400226/81089820-d49fc580-8eca-11ea-9f77-e62e01788df5.png)

**Comment by guillaume-chevalier** [comment]
@alexbrillant should we remove it now?

**Comment by guillaume-chevalier** [comment]
Fixed.
